# generated by fastapi-codegen:
#   filename:  inventories.yaml
#   timestamp: 2025-06-19T06:46:08+00:00

from __future__ import annotations

from abc import ABC, abstractmethod

import uvicorn
from fastapi import FastAPI, HTTPException

from .models import Item


class AppController(ABC):

    def get_inventory_bla(
        self,
    ) -> Item:
        """This method should be implemented by the subclass."""
        raise HTTPException(status_code=404, detail="Not implemented")

    def get_inventory(
        self,
    ) -> Item:
        """This method should be implemented by the subclass."""
        raise HTTPException(status_code=404, detail="Not implemented")


class IntegrationApp:

    def __init__(self):
        self.app = FastAPI(
            title="IntA Inventory API",
            version="1.0.0",
            description="API for managing inventory items in the IntA system.",
        )

    def set_controller(self, controller: AppController) -> IntegrationApp:
        """Set the controller for the application."""
        self.controller = controller
        return self

    def run(self):
        uvicorn.run(self.app)

    async def get_inventory_bla(
        self,
    ) -> Item:
        """
        Get all inventory items

        """
        return self.controller.get_inventory_bla()

    async def get_inventory(
        self,
    ) -> Item:
        """
        Get all inventory items

        """
        return self.controller.get_inventory()

    def setup_routes(self) -> IntegrationApp:
        """Set up the API routes for the integration."""

        self.app.add_api_route(
            "/blabla_endpoint",
            self.get_inventory_bla,
            response_model=Item,
            methods=["get"],
        )

        self.app.add_api_route(
            "/inventory", self.get_inventory, response_model=Item, methods=["get"]
        )

        return self
