# generated by fastapi-codegen:
#   filename:  inventories.yaml
#   timestamp: 2025-06-18T21:32:09+00:00

from __future__ import annotations

from fastapi import FastAPI

from .models import Item

app = FastAPI(
    title="IntA Inventory API",
    version="1.0.0",
    description="API for managing inventory items in the IntA system.",
)


class AppController:

    def get_inventory_bla(
        self,
    ) -> Item:
        """This method should be implemented by the subclass to return an Item."""
        raise NotImplementedError("This method should be implemented by the subclass.")

    def get_inventory(
        self,
    ) -> Item:
        """This method should be implemented by the subclass to return an Item."""
        raise NotImplementedError("This method should be implemented by the subclass.")


class IntegrationApp:

    def __init__(self, controller: AppController):
        self.controller = controller
        self.setup_routes()

    async def get_inventory_bla(
        self,
    ) -> Item:
        """
        Get all inventory items

        """
        return self.controller.get_inventory_bla()

    async def get_inventory(
        self,
    ) -> Item:
        """
        Get all inventory items

        """
        return self.controller.get_inventory()

    def setup_routes(self):
        """Set up the API routes for the integration."""

        app.add_api_route(
            "/blabla_endpoint",
            self.get_inventory_bla,
            response_model=Item,
            methods=["get"],
        )

        app.add_api_route(
            "/inventory", self.get_inventory, response_model=Item, methods=["get"]
        )
