# generated by fastapi-codegen:
#   filename:  centra_contracts/inventories.yaml
#   timestamp: 2025-06-18T21:32:09+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Item(BaseModel):
    name: str = Field(..., description='The name of the inventory item')
    description: str = Field(
        ..., description='A detailed description of the inventory item'
    )
    price: float = Field(..., description='The price of the inventory item')
    in_stock: bool = Field(
        ..., description='Whether the inventory item is in stock or not'
    )
